version: "3.9"

services:  
  xupnpd:
    image: fdelucia/xupnpd
    container_name: xupnp
    network_mode: host
    volumes:
      - /playlists/:/xupnpd/playlists/
      - /config/:/xupnpd/config/
    restart: always

volumes:
   playlists:
   config:
